# Book settings
title: Big Data for Sports and Human Movement Sciences Practicals (RUG)
author: University of Groningen, Department of Human Movement Sciences
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/Alek050/big_data_practicals 
  path_to_book: practicals_jn_book  
  branch: main  

html:
  use_issues_button: true
  use_repository_button: true
