on:
  pull_request:
    branches:
      - '*' # Pull requests to all branches

jobs:
  build-jupyter-book:
    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r practicals_jn_book/requirements.txt
          pip install jupyter-book

      - name: Build documentation (only on macos-latest)
        run: jupyter-book build practicals_jn_book --all
